#!/bin/sh

# Taken from tpopes effortless ctags
# https://tbaggery.com/2011/08/08/effortless-ctags-with-git.html

set -e
PATH="/usr/local/bin:$PATH"
dir="`git rev-parse --git-dir`"
trap 'rm -f "$$.tags"' EXIT
git ls-files | \
  ctags --tag-relative -L - -f"$$.tags"
mv "$$.tags" "tags"
